### ISSUE TITLE
Indent Guide is misaligned with invisibles turned on

### ISSUE THREAD

**Issue by mstewart6** [elixir-editors/language-elixir#108]
![invisibles](https://user-images.githubusercontent.com/18093356/46485436-44b30a80-c7c1-11e8-9818-5bd9f7c44a34.png)

When using the indent guide with invisibles turned on, the guide lines get misaligned when blank lines surround non-blank lines. The guide lines get shifted over by 1px to the right for the guides with invisibles (see attached picture for reference).

Switching between themes when the grammar is set to Elixir does not resolve this, but changing the grammar to the default grammar (Plain Text) does, so it appears to be something related to this language package. Turning off invisibles also causes the guide lines to re-align properly.

**Comment by keathley** [comment]
@mstewart6 I'm not able to see this issue on my machine. Are you using a specific font that may be doing this?

Here's what I'm seeing on my machine:
<img width="337" alt="screen shot 2018-10-05 at 10 33 23 am" src="https://user-images.githubusercontent.com/1642095/46541505-367cf100-c88a-11e8-92ee-faef7ccff8f7.png">

**Comment by mstewart6** [comment]
@keathley No, I am using the default font. I have my font as size 13 (but I dropped it to the default as well to no effect). Using OSX 10.13 High Sierra, if platform matters.

The issue isn't with consecutive lines with spaces, it's when a completely blank line is adjacent to one with leading spaces. It is possible that it only affects heredocs, as that is where I am most consistent in reproducing it.

![image](https://user-images.githubusercontent.com/18093356/46543014-77bed200-c885-11e8-9281-6f7829dd570a.png)

**Comment by keathley** [comment]
Same setup, with default font size set to 13:

![image](https://user-images.githubusercontent.com/1642095/46543582-3c290580-c88f-11e8-98e7-c5940fa46979.png)

Have you tried disabling different packages to see if that effects this?

**Comment by mstewart6** [comment]
Aha, looks like there is a [fonts](https://atom.io/packages/fonts) package for monospace fonts that was causing this (but only for Elixir oddly). Disabling that makes everything look correct again.

Note that your latest repro does not have blank lines surrounding the indented one though. The lack of spaces was what was triggering it for me, though it now appears that the font package was to blame.

**Comment by keathley** [comment]
Ah I see. I think I've matched yours now:

![image](https://user-images.githubusercontent.com/1642095/46551556-15c29480-c8a6-11e8-994f-4a15d9524818.png).

In any case it sounds like its an issue with the fonts package. I'd open an issue up with them :+1:.
