### ISSUE TITLE
.heex support not yet available via Atom package management GUI

### ISSUE THREAD

**Issue by njwest** [elixir-editors/language-elixir#113]
Would be nice to get this latest version of language-elixir onto the Atom registry, but in the meantime this package with HEEX support can be installed via the following steps:

1. Uninstall the language-elixir from Atom
2. Run the following CLI commands:

```shell
git clone git@github.com:elixir-editors/language-elixir.git

cd language-elixir

apm install
 
apm link .
```

**Comment by sn3p** [comment]
Yes please!

**Comment by keathley** [comment]
sorry about that. I had to get apm and all of that noise set up on this computer. It should be published now.

**Comment by keathley** [comment]
also, if anyone in this thread would like to take over maintenance of this project let me know.

**Comment by sn3p** [comment]
> also, if anyone in this thread would like to take over maintenance of this project let me know.

You could advertise this in the README.md which also shows in APM. Might get some more attention that way.
