### ISSUE TITLE
Capturing function arguments?

### ISSUE THREAD

**Issue by phyllisstein** [elixir-editors/language-elixir#86]
Hey there! I hate to be a nudzh, but I was hoping I could suggest a small enhancement to this package. I noticed that the Sublime Text Elixir package has a scope for arguments in a function definition, but that the Atom grammar does not:

<img width="1192" alt="screen shot 1" src="https://cloud.githubusercontent.com/assets/2207980/23694393/abf6f3bc-03a7-11e7-9f4b-3365aa68a5af.png">

![screen shot 2](https://cloud.githubusercontent.com/assets/2207980/23694397/ade14e3e-03a7-11e7-9f82-372aab826814.png)

Personally I like being able to assign highlighting to arguments---I guess it's partly force of habit at this point, but I find that being able to quickly distinguish them from text helps with visual grepping.

(Plus it's purdy. 😍 )

Sadly I don't know Elixir or Atom grammars well enough to fork it and take a crack. But I was wondering if there was a path to creating similar functionality for Atom. Thanks in advance for taking it under consideration!

**Comment by keathley** [comment]
Thanks @phyllisstein I'll take a look at it.
